SELECT C.ComplianceMonitoringId,C.ProgramSystemAcronym,C.ProgramSystemIdentifier,C.FederalStatuteCode,C.ActivityTypeCode,
C.CategoryCode,C.ComplianceMonitoringDate,C.StartDate,C.InspectionTypeCode,C.ActivityName,
C.ActionReasonCode,C.AgencyTypeCode,C.AgencyCode,C.ProgramCode,C.EPAAssistanceIndicator,
C.StateFederalJointIndicator,C.JointInspectionReasonCode,C.LeadParty,C.Days,C.Hours,
C.ActionOutcomeCode,C.InspectionRatingCode,C.NationalPrioritiesCode,C.MultimediaIndicator,C.FederalFacilityIndicator,
C.FederalFacilityIndicatorComment,C.InspectionUserDefinedField1,C.InspectionUserDefinedField2,C.InspectionUserDefinedField3,C.InspectionUserDefinedField4,
C.InspectionUserDefinedField5,C.InspectionUserDefinedField6,C.PlannedStartDate,C.PlannedEndDate,C.EPARegion,
C.LawSectionCode,C.MediaTypeCode,C.RegionalPriorityCode, SIC.SICCode, NAICS.NAICSCode, 
C.LeadAgencyCode,C.InspectionCommentText,C.SensitiveCommentText,C.TransactionID,
C.OtherProgramDescriptionText, AirStackTestData.StackTestStatusCode, AirStackTestData.ConductorTypeCode, AirStackTestData.StackIdentifier,AirStackTestData.StackTestPurposeCode,
AirStackTestData.OtherStackTestPurposeName,AirStackTestData.ObservedAgencyTypeCode,AirStackTestData.ReportReceivedDate,AirStackTestData.ResultsReviewedDate,TestResultsData.TestResultsDataId, 
TestResultsData.AirTestedPollutantCode, TestResultsData.MethodCode,TestResultsData.TestResultCode,ComplianceMonitoringContact.ContactId,Contact.AffiliationTypeText,
Contact.FirstName,Contact.MiddleName,Contact.LastName, Contact.IndividualTitleText,Contact.OrganizationFormalName,
Contact.StateCode,Telephone.TelephoneID,Telephone.TelephoneNumberTypeCode,Telephone.TelephoneNumber,Telephone.TelephoneExtensionNumber,
InspectionGovernmentContact.ContactId AS GContactId,GContact.AffiliationTypeText AS GAffiliationTypeText,GContact.ElectronicAddressText AS GElectronicAddressText,[Transaction].TransactionType,CONVERT(VARCHAR(30),[Transaction].TransactionTimestamp, 126) as TransactionTimestamp,
ComplianceMonitoringCodeId, CodeName, CodeValue, 
null as SubactivityId, null as SubactivityTypeCode,null as SubactivityPlannedDate, null as SubactivityDate, null as CitationId, 
null as CitationTitle, null as CitationPart, null as CitationSection,null as InspectionConclusionId, null as DeficienciesObservedInd, 
null as DeficiencyCommunicatedFacilityInd,null as FacilityActionObservedInd, null as NationalPolicyGeneralAssistanceInd,null as NationalPolicySiteSpecificAssistanceInd,null as InspectionConclusionCodeId,
null as CodeName,null as CodeValue, null as CAFOInspectionId, null as CAFOClassificationCode, null as IsAnimalFacilityTypeCAFOInd,
null as CAFODesignationDate, null as CAFODesignationReasonText, null as CSOInspectionId, null as DryOrWetWeatherInd,null as PermittedFeatureId, 
null as CSOOverflowLocationStreet, null as DurationCSOOverflowEvent, null as DischargeVolumeTreated,null as DischargeVolumeUntreated, null as CorrectiveActionTakenDescriptionText, 
null as InchesPrecipitation,null AS CSO_lati, null AS CSO_Longi, null as SSOInspectionId,null as CauseSSOOverflowEvent, 
null as SSOOverflowLocationStreet, null as DurationSSOOverflowEvent, null as SSOVolume,null as NameReceivingWater, null as ImpactSSOEvent,
null as SSOStepId, null as StepsReducePreventMitigate,null as OtherStepsReducePreventMitigate, null AS SSO_Lati, null AS SSO_Longi,
null as SSOSystemComponentId, null as SystemComponent, null as OtherSystemComponent,null as PretreatmentId, null as SUOReference, 
null as SUODate, null as AcceptanceHazardousWaste,null as AcceptanceNonHazardousIndustrialWaste, null as AcceptanceHauledDomesticWastes, null as AnnualPretreatmentBudget,
null as InadequacySamplingInspectionInd, null as AdequacyPretreatmentResources, null as DeficienciesIdentifiedDuringIUFileReview,null as ControlMechanismDeficiencies, null as LegalAuthorityDeficiencies,
null as DeficienciesInterpretationApplicationPretreatmentStandards,null as DeficienciesDataManagementPublicParticipation, null as ViolationIUScheduleRemedialMeasures,null as FormalResponseViolationIUScheduleRemedialMeasures, null as AnnualFrequencyInfluentToxicantSampling,
null as AnnualFrequencyEffluentToxicantSampling,
null as AnnualFrequencySludgeToxicantSampling, null as NumberSIUs,null as SIUsWithoutControlMechanism, null as SIUsNotInspected,null as SIUsNotSampled, 
null as SIUsOnSchedule,null as SIUsSNCWithPretreatmentStandards, null as SIUsSNCWithReportingRequirements, null as SIUsSNCWithPretreatmentSchedule,null as SIUsSNCPublishedNewspaper, 
null as ViolationNoticesIssuedSIUs, null as AdministrativeOrdersIssuedSIUs,null as CivilSuitsFiledAgainstSIUs,null as StormWaterConstructionInspectionId,null as ProjectTypeCode, 
null as ProjectTypeCodeOtherDescription,null as EstimatedStartDate, null as EstimatedCompleteDate,null as EstimatedAreaDisturbedAcresNumber, null as ProjectPlanSizeCode,
null as StormWaterMS4InspectionId, null as LegalEntityTypeCode, null as MS4PermitClassCode,null as MS4TypeCode, null as MS4AcreageCoveredNumber,
null as MS4PopulationServedNumber,null as UrbanizedAreaIncorporatedPlaceName
FROM ComplianceMonitoring C LEFT JOIN ComplianceMonitoringCode ON C.ComplianceMonitoringId = ComplianceMonitoringCode.ComplianceMonitoringId LEFT JOIN SIC ON SIC.ComplianceMonitoringId = C.ComplianceMonitoringId LEFT JOIN NAICS ON NAICS.ComplianceMonitoringId = C.ComplianceMonitoringId LEFT JOIN AirStackTestData ON C.ComplianceMonitoringId = AirStackTestData.ComplianceMonitoringId LEFT JOIN TestResultsData ON C.ComplianceMonitoringId = TestResultsData.ComplianceMonitoringId LEFT JOIN ComplianceMonitoringContact ON C.ComplianceMonitoringId = ComplianceMonitoringContact.ComplianceMonitoringId LEFT JOIN Contact ON ComplianceMonitoringContact.ContactId = Contact.ContactID LEFT JOIN Telephone ON Contact.ContactID = Telephone.ContactID LEFT JOIN InspectionGovernmentContact ON C.ComplianceMonitoringId = InspectionGovernmentContact.ComplianceMonitoringId LEFT JOIN Contact GContact ON InspectionGovernmentContact.ContactId = GContact.ContactID INNER JOIN [Transaction] ON C.TransactionID = [Transaction].TransactionID INNER JOIN SubmissionStatus ON C.ComplianceMonitoringId = SubmissionStatus.ID WHERE C.MonitoringType='Federal' AND  SubmissionStatus.TableName='ComplianceMonitoring' AND SubmissionStatus.Status is NULL AND SubmissionStatus.Operation <> 'delete' AND SubmissionStatus.ID in ('{$ComplianceMonitoringID}') AND [Transaction].TransactionTimestamp between '{$fromDate}' and '{$toDate}' UNION All
SELECT C.ComplianceMonitoringId,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,C.TransactionID, 
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,null,null,
null,null,null,
Subactivity.SubactivityId, Subactivity.SubactivityTypeCode,Subactivity.SubactivityPlannedDate, Subactivity.SubactivityDate, Citation.CitationId, 
Citation.CitationTitle, Citation.CitationPart, Citation.CitationSection,InspectionConclusion.InspectionConclusionId, InspectionConclusion.DeficienciesObservedInd, 
InspectionConclusion.DeficiencyCommunicatedFacilityInd,InspectionConclusion.FacilityActionObservedInd, InspectionConclusion.NationalPolicyGeneralAssistanceInd,InspectionConclusion.NationalPolicySiteSpecificAssistanceInd, InspectionConclusionCode.InspectionConclusionCodeId, 
InspectionConclusionCode.CodeName,InspectionConclusionCode.CodeValue, CAFOInspection.CAFOInspectionId, CAFOInspection.CAFOClassificationCode, CAFOInspection.IsAnimalFacilityTypeCAFOInd,
CAFOInspection.CAFODesignationDate, CAFOInspection.CAFODesignationReasonText, CSOInspection.CSOInspectionId, CSOInspection.DryOrWetWeatherInd,CSOInspection.PermittedFeatureId, 
CSOInspection.CSOOverflowLocationStreet, CSOInspection.DurationCSOOverflowEvent, CSOInspection.DischargeVolumeTreated,CSOInspection.DischargeVolumeUntreated, CSOInspection.CorrectiveActionTakenDescriptionText, 
CSOInspection.InchesPrecipitation,GeographicCoordinate.LatitudeMeasure, GeographicCoordinate.LongitudeMeasure, SSOInspection.SSOInspectionId,SSOInspection.CauseSSOOverflowEvent, 
SSOInspection.SSOOverflowLocationStreet, SSOInspection.DurationSSOOverflowEvent, SSOInspection.SSOVolume,SSOInspection.NameReceivingWater, SSOInspection.ImpactSSOEvent, 
SSOStep.SSOStepId, SSOStep.StepsReducePreventMitigate,SSOStep.OtherStepsReducePreventMitigate, GeographicCoordinate_1.LatitudeMeasure, GeographicCoordinate_1.LongitudeMeasure,
SSOSystemComponent.SSOSystemComponentId, SSOSystemComponent.SystemComponent, SSOSystemComponent.OtherSystemComponent,Pretreatment.PretreatmentId, Pretreatment.SUOReference, 
Pretreatment.SUODate, Pretreatment.AcceptanceHazardousWaste,Pretreatment.AcceptanceNonHazardousIndustrialWaste, Pretreatment.AcceptanceHauledDomesticWastes, Pretreatment.AnnualPretreatmentBudget,
Pretreatment.InadequacySamplingInspectionInd, Pretreatment.AdequacyPretreatmentResources, Pretreatment.DeficienciesIdentifiedDuringIUFileReview,Pretreatment.ControlMechanismDeficiencies, Pretreatment.LegalAuthorityDeficiencies,
Pretreatment.DeficienciesInterpretationApplicationPretreatmentStandards,Pretreatment.DeficienciesDataManagementPublicParticipation, Pretreatment.ViolationIUScheduleRemedialMeasures,Pretreatment.FormalResponseViolationIUScheduleRemedialMeasures,Pretreatment.AnnualFrequencyInfluentToxicantSampling,
Pretreatment.AnnualFrequencyEffluentToxicantSampling,
Pretreatment.AnnualFrequencySludgeToxicantSampling,Pretreatment.NumberSIUs,Pretreatment.SIUsWithoutControlMechanism, Pretreatment.SIUsNotInspected, Pretreatment.SIUsNotSampled, 
Pretreatment.SIUsOnSchedule,Pretreatment.SIUsSNCWithPretreatmentStandards, Pretreatment.SIUsSNCWithReportingRequirements, Pretreatment.SIUsSNCWithPretreatmentSchedule,Pretreatment.SIUsSNCPublishedNewspaper, 
Pretreatment.ViolationNoticesIssuedSIUs, Pretreatment.AdministrativeOrdersIssuedSIUs,Pretreatment.CivilSuitsFiledAgainstSIUs, StormWaterConstructionInspection.StormWaterConstructionInspectionId,StormWaterConstructionInspection.ProjectTypeCode, 
StormWaterConstructionInspection.ProjectTypeCodeOtherDescription,StormWaterConstructionInspection.EstimatedStartDate, StormWaterConstructionInspection.EstimatedCompleteDate,StormWaterConstructionInspection.EstimatedAreaDisturbedAcresNumber, StormWaterConstructionInspection.ProjectPlanSizeCode,
StormWaterMS4Inspection.StormWaterMS4InspectionId,StormWaterMS4Inspection.LegalEntityTypeCode, StormWaterMS4Inspection.MS4PermitClassCode,StormWaterMS4Inspection.MS4TypeCode, StormWaterMS4Inspection.MS4AcreageCoveredNumber,
StormWaterMS4Inspection.MS4PopulationServedNumber,StormWaterMS4Inspection.UrbanizedAreaIncorporatedPlaceName
FROM ComplianceMonitoring C INNER JOIN [Transaction] ON C.TransactionID = [Transaction].TransactionID INNER JOIN Subactivity ON C.ComplianceMonitoringId = Subactivity.ComplianceMonitoringId LEFT JOIN Citation ON C.ComplianceMonitoringId = Citation.ComplianceMonitoringId LEFT JOIN CAFOInspection ON C.ComplianceMonitoringId = CAFOInspection.ComplianceMonitoringId LEFT JOIN CSOInspection ON C.ComplianceMonitoringId = CSOInspection.ComplianceMonitoringId LEFT JOIN CSOInspectioGeographicCoordinate ON CSOInspection.CSOInspectionId = CSOInspectioGeographicCoordinate.CSOInspectionId LEFT JOIN GeographicCoordinate ON CSOInspectioGeographicCoordinate.GeographicCoordinateID = GeographicCoordinate.GeographicCoordinateID LEFT JOIN InspectionConclusion ON C.ComplianceMonitoringId = InspectionConclusion.ComplianceMonitoringId LEFT JOIN InspectionConclusionCode ON InspectionConclusion.InspectionConclusionId = InspectionConclusionCode.InspectionConclusionId LEFT JOIN Pretreatment ON C.ComplianceMonitoringId = Pretreatment.ComplianceMonitoringId LEFT JOIN SSOInspection ON C.ComplianceMonitoringId = SSOInspection.ComplianceMonitoringId LEFT JOIN SSOInspectionGeographicCoordinate ON SSOInspection.SSOInspectionId = SSOInspectionGeographicCoordinate.SSOInspectionId LEFT JOIN GeographicCoordinate GeographicCoordinate_1 ON GeographicCoordinate.GeographicCoordinateID = SSOInspectionGeographicCoordinate.GeographicCoordinateID LEFT JOIN SSOStep ON SSOInspection.SSOInspectionId = SSOStep.SSOInspectionId LEFT JOIN SSOSystemComponent ON SSOInspection.SSOInspectionId = SSOSystemComponent.SSOInspectionId LEFT JOIN StormWaterConstructionInspection ON C.ComplianceMonitoringId = StormWaterConstructionInspection.ComplianceMonitoringId LEFT JOIN StormWaterMS4Inspection ON C.ComplianceMonitoringId = StormWaterMS4Inspection.ComplianceMonitoringId INNER JOIN SubmissionStatus ON C.ComplianceMonitoringId = SubmissionStatus.ID WHERE C.MonitoringType='Federal' AND  SubmissionStatus.TableName='ComplianceMonitoring' AND SubmissionStatus.Status is NULL AND SubmissionStatus.Operation <> 'delete' AND SubmissionStatus.ID in ('{$ComplianceMonitoringID}') AND [Transaction].TransactionTimestamp between '{$fromDate}' and '{$toDate}'
						